name: CI

on: [push]

jobs:

  shell_exploration:
    name: Launch Shell Exploration
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Calculate duration - zsh
      run: |
        zsh ./shell/duration.sh
    - name: Calculate duration - bash
      run: |
        bash ./shell/duration.sh
